- hosts: all
  vars:
    timesync_ntp_servers:
      - ntp.ntsc.ac.cn
      - ntp.aliyun.com
    registry_mirrors: https://docker.mirrors.ustc.edu.cn/
    insecure_registries: http://192.168.1.115
    k8s_image_Repository: registry.aliyuncs.com/google_containers
    k8s_clusterName: ansible-k8s
    k8s_serviceSubnet: 10.96.0.0/12
    k8s_podSubnet: 10.244.0.0/16
    calico_ipv4_cidr: 10.244.0.0/16
    calico_interface: ens33
  roles:
    - prepare
    - docker-ce
    - kubernetes
    - calico
