- name: Install chrony
  package:
    name: chrony
    state: present

- name: Generate chrony.conf file
  template:
    src: chrony.conf.j2
    dest: "/etc/chrony.conf"
    mode: 0644

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted
