- name: Install base packages
  yum:
    name:
      - vim # 一个很好用的Linux文本编辑器
      - bash-completion # bash命令补全工具
      - net-tools # 包含常用的网络配置工具
      - conntrack-tools # ipvs 模式需要
      - libseccomp # 安装containerd需要
      - nfs-utils # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - rsync # 文件同步工具，分发证书等配置文件需要
      - socat # 用于port forwarding
    state: present
